services:
  - type: web
    name: your-service-name
    env: python
    plan: free   # or starter
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py   # or gunicorn / uvicorn
    pythonVersion: 3.12
